CREATE TABLE "asistencias" (asistenciaID INTEGER PRIMARY KEY AUTOINCREMENT,   clienteID INTEGER,   fechaIngreso TEXT,   horaIngreso TEXT, grupoID INTEGER, claseID INTEGER, usuarioID INTEGER, asistio BOOLEAN DEFAULT 0, entrada INTEGER, salida INTEGER, salonID INTEGER);
CREATE TABLE "clases" (claseID INTEGER PRIMARY KEY AUTOINCREMENT,  instructorID INTEGER,  grupoID INTEGER,  salonID INTEGER, descripcion TEXT);
CREATE TABLE clases_asistencia (ID INTEGER PRIMARY KEY AUTOINCREMENT, claseID INTEGER, fecha TEXT, usuarioID INTEGER);
CREATE TABLE "clientes" (clienteID INTEGER PRIMARY KEY AUTOINCREMENT,    nombres TEXT,    cedula TEXT,    telefonos TEXT,    direccion TEXT,    fechaNacimiento TEXT,   fechaRegistro TEXT,   grupoID INTEGER,   meta TEXT);
CREATE TABLE "config" (key TEXT PRIMARY KEY, value TEXT);
INSERT INTO config (key,value) VALUES ('correlativo','21');
INSERT INTO config (key,value) VALUES ('impresion_anchoPapel','300');
INSERT INTO config (key,value) VALUES ('razon_social','EMPRESA');
INSERT INTO config (key,value) VALUES ('rif','J-0000000-0');
INSERT INTO config (key,value) VALUES ('impresion_fuente','3');
INSERT INTO config (key,value) VALUES ('sonidos','0');
CREATE TABLE "facturas" (facturaID INTEGER PRIMARY KEY AUTOINCREMENT,   clienteID INTEGER,   fecha TEXT,   usuarioID INTEGER, correlativo INTEGER, monto REAL);
CREATE TABLE "grupos" (grupoID INTEGER PRIMARY KEY AUTOINCREMENT, descripcion TEXT, nombre TEXT, renta REAL);
CREATE TABLE "horarios" (horarioID INTEGER PRIMARY KEY AUTOINCREMENT,  grupoID INTEGER,  tipo INTEGER,  entrada INTEGER,  salida INTEGER,  dias TEXT, claseID INTEGER);
CREATE TABLE "instructores" (instructorID INTEGER PRIMARY KEY AUTOINCREMENT,   nombres TEXT,   cedula TEXT,   telefonos TEXT);
CREATE TABLE "pagos" (pagoID INTEGER PRIMARY KEY AUTOINCREMENT, facturaID INTEGER, clienteID INTEGER, descripcion TEXT, monto REAL, fecha TEXT, cantidad REAL, usuarioID INTEGER, pendiente BOOLEAN, hash TEXT);
CREATE TABLE "productos" (productoID INTEGER PRIMARY KEY AUTOINCREMENT, descripcion TEXT, cantidad INTEGER, monto REAL);
CREATE TABLE salones (salonID INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT);
CREATE TABLE "tareas" (tareaID INTEGER PRIMARY KEY AUTOINCREMENT,   type TEXT,   tipo INTEGER,   dia INTEGER,   meta TEXT,   tarea TEXT);
CREATE TABLE usuarios (usuarioID INTEGER PRIMARY KEY AUTOINCREMENT, usuario TEXT, pass TEXT, acceso INTEGER, nombre TEXT);
INSERT INTO usuarios (usuarioID,usuario,pass,acceso,nombre) VALUES (1,'admin','admin',0,'Administrador');